name: 'TelegramBridge'
description: 'Send GitHub Updates to Telegram, see readme for step by step instructions'
author: 'gokuldas027'
inputs: 
  chat: 
    description: 'Chat to send: chat id or @channel_name/add to secrets'
    default: # ${{ secrets.chat }}
    required: True
  token: 
    description: 'Telegram Bot token/add to secrets'
    default: # ${{ secrets.token }}
    required: True
  message:
    description: 'Message'
    default: 'Something happened'
    required: True

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'  
  color: 'blue'
